### ISSUE TITLE
support velodyne16 laser radar

### ISSUE THREAD

**Issue by af-doom** [hku-mars/FAST-LIVO#10]
Outstanding work. Does this code support velodyne16 laser radar, external IMU and realsense camera? If so, how should the parameters be designed? What is the base coordinate system of the rotation matrix in the configuration file

**Comment by XW-HKU** [comment]
You can support velodyne following the code of fast-lio2. This repo is only focusing on visual part.

**Comment by af-doom** [comment]
> You can support velodyne following the code of fast-lio2. This repo is only focusing on visual part.

I modified the code for processing radar messages according to Fast-lio2. The following errors still occur for velodye16. Can you give me some advice
