### ISSUE TITLE
禾赛32线雷达+海康相机 运行问题

### ISSUE THREAD

**Issue by tanble** [hku-mars/FAST-LIVO#103]
非常感谢之前作者的支持，现在在不使用VIO子系统的时候，效果已经很好了。所以在此基础上我准备加上视觉部分，以求完成 禾赛+海康 的适配。在适配的过程中，遇到了一些问题，想请教一下。
1、请问相机的外参标定是camera2imu吗，看着fast_livo是以imu为全局框架的，所以这些传感器的标定是不是都是往imu变换的呢？那这种 情况下，使用仓库内的lidar_camera_calib工具标定的参数是不是可以直接应用到FAST_LIVO的工作中。

2、我目前使用的相机外参参数是由仓库内的lidar_camera_calib得到的，点云着色效果模糊，并且pos跑飞的概率极大，我通过查询以往的issue，总结了一些情况：1.可能是camera和lidar错帧，2.外参标定结果，3.时间未同步，除此之外，不知道还有哪些可能性导致VIO子系统工作异常？

**Comment by xuankuzcr** [comment]
1. 相机和LiDAR外参的定义在这里#37，lidar_camera_calib的外参出来直接替代参数文件的Rcl Pcl就行
2.  其他情况可能是视觉的观测不够好，outlier过多等等情况，要具体数据具体分析
