### ISSUE TITLE
How to run our own data (How to generate the .bag data like the sample data)?

### ISSUE THREAD

**Issue by hama-agrmet** [hku-mars/FAST-LIVO#106]
I'm trying to run the FAST-LIVO with our own data.
Now I have a complete set of equipment as following site (https://github.com/ziv-lin/rxlive_handheld).
However, I can't get the .bag data with RGB camera data (img_topic).
Could you please tell me how to save the LiDAR data and RGB camera data together in a .bag?

**Comment by Es1erda** [comment]
Thank you for your interest in this work.
You can first use `rostopic list `to check if the relevant topics are being published correctly. Then, use `rosbag record -a` to record all topics.
Additionally, you might be interested in following our open-source handheld project: [](https://github.com/sheng00125/LIV_handhold).
