### ISSUE TITLE
fast-livo运行自己的数据集时会产生漂移现象

### ISSUE THREAD

**Issue by Hohaizzz** [hku-mars/FAST-LIVO#109]
作者你好，感谢您对此代码的开源，目前正在使用zed2和avia进行自己的数据集录制，运行fast-livo时会产生漂移现象。其中相机和激光雷达的外参关系以按camear-lidar-calibration标定完成，使用livox_ros_driver_for_R2LIVE对雷达进行录制，当我只对激光雷达avia和zed2进行录制时，会产生偏移，但不是很离谱。
![微信图片_20240722165945](https://github.com/user-attachments/assets/59d6f014-47cf-4f31-9811-4380d0cde4a5)
但当我再打开一个红外相机，再bag中添加录制红外照片的话题时，就直接飘了，不知道是不是和电脑内存之内的原因.
![微信图片_20240722165930](https://github.com/user-attachments/assets/ea5d97b0-af3e-45a0-84c9-3baa81457ceb)
下面是我的config配置：
![微信图片_20240722165942](https://github.com/user-attachments/assets/fcf25d81-4204-42ae-bf4a-8f4893d12850)
希望得到您的回复！！

**Comment by xuankuzcr** [comment]
您好，感谢您对我们工作的兴趣！
1. 先检查外参标定效果，可以根据静止场景上色点云来判断。
2. 相机和LiDAR之间要做好硬件同步，LiDAR和相机的driver，以及同步方法参考这个[链接](https://github.com/sheng00125/LIV_handhold)。不要使用livox_ros_driver_for_R2LIVE。

你展示的两种点云效果都是跑飞了的状态，建议检查完外参和时差之后再分析数据。
