### ISSUE TITLE
LiDAR Camera no common FOV

### ISSUE THREAD

**Issue by LiuYMUNI** [hku-mars/FAST-LIVO#112]
Dear authors, thanks a lot for your great work. I got a question about the FOV of LiDAR and camera. Is it possible to run FAST-LIVO with a LiDAR installed at the front of the agent and camera and the tail of the agent. I mean, the two sensors do not share  FOV. Is it possible for FAST-LIVO to perform state estimation without modification in such configuration?

**Comment by xuankuzcr** [comment]
Thank you for your interest. Due to the tight coupling of the camera and LiDAR at the measurement level, we do not support installation configurations where the camera and LiDAR have no overlapping FoV.

**Comment by xuankuzcr** [comment]
Hi, you can close this issue if there are no further concerns.

**Comment by LiuYMUNI** [comment]
> Hi, you can close this issue if there are no further concerns.

Thanks for your support and reminding.
