### ISSUE TITLE
Confuse about "flg_EKF_inited" flag.

### ISSUE THREAD

**Issue by OliverShaoPT** [hku-mars/FAST-LIVO#117]
for (iterCount = -1; iterCount < NUM_MAX_ITERATIONS && **flg_EKF_inited**; iterCount++)  {
   .....
   /*** Iterative Kalman Filter Update ***/
   if ( **!flg_EKF_inited** ){
      ...
   }
}

**Comment by xuankuzcr** [comment]
It means that the EKF update should be performed after the initialization is successfully completed.

**Comment by OliverShaoPT** [comment]
> It means that the EKF update should be performed after the initialization is successfully completed.

The inside "!flg_EKF_inited" condition will not be triggered, as the BIG for_loop's condition contain "flg_ekf_inited".

**Comment by OliverShaoPT** [comment]
> It means that the EKF update should be performed after the initialization is successfully completed.

The inside if condition "!flg_EKF_inited" won't be triggered as the outside big for_loop's conditions contain "flg_EKF_inited".
I am confused about:
1, Is the initialization process in the EKF update loop useless? 
or
2, Should I delete the  flg_EKF_inited condition in the EKF iterated for_loop?

![image](https://github.com/user-attachments/assets/622becb9-5856-4110-8e9a-c1a7acef8dbb)
![image](https://github.com/user-attachments/assets/9208c0dc-fefc-4b77-b3ca-33a10a67356c)

**Comment by xuankuzcr** [comment]
You seem to be right. I think it's safe to delete it without any issues.

**Comment by OliverShaoPT** [comment]
Thanks!
