### ISSUE TITLE
有关Mid70和D435i实时运行的问题

### ISSUE THREAD

**Issue by QSRNC001** [hku-mars/FAST-LIVO#118]
作者您好，我在使用Mid70和D435i实时运行的过程中，如果不使用VIO模块，即配置文件中img_enable : 0，此时可以正常建图和定位，但是如果启用了VIO模块，rviz中没有任何点云显示。我的配置文件和运行时打印的结果如下，请您看看是什么原因造成的，谢谢
![2024-08-26 14-45-11 的屏幕截图](https://github.com/user-attachments/assets/bdf0370d-a075-4fe3-b098-400e7692c81e)
![2024-08-26 14-45-51 的屏幕截图](https://github.com/user-attachments/assets/7f97c0f1-cb35-432e-a248-854c2e71431c)

**Comment by FnLime** [comment]
请问是如何解决的 目前我也碰到了同样的问题

**Comment by WMAAA** [comment]
我也遇到了这个问题😰

**Comment by m78x** [comment]
有无佬提供下思路，也这个问题不知道怎么搞
