### ISSUE TITLE
odometry结果

### ISSUE THREAD

**Issue by duanqigeng** [hku-mars/FAST-LIVO#122]
作者您好!在观看lidar-selection的逻辑之后,updateFrameState(StatesGroup state),我发现odometry结果是标定到相机,想请问是这样吗?

**Comment by xuankuzcr** [comment]
您好，“odometry结果是标定到相机”这句话没看懂是什么意思，odom的结果是imu在world系下的pose。

**Comment by duanqigeng** [comment]
谢谢您的解答
