### ISSUE TITLE
The following error occurs when using velodyen16

### ISSUE THREAD

**Issue by af-doom** [hku-mars/FAST-LIVO#13]
![2022-11-14 22-28-49 的屏幕截图](https://user-images.githubusercontent.com/91470350/201685475-49582777-2f47-40aa-8146-d7be1da82903.png)

**Comment by XW-HKU** [comment]
You can support velodyne following the code of fast-lio2. This repo is only focusing on visual part.

**Comment by af-doom** [comment]
There is no problem when using fast-lio2 for my data



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 15, 2022 02:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hku-mars/FAST-LIVO] The following error occurs when usingvelodyen16 (Issue #13)




 
You can support velodyne following the code of fast-lio2. This repo is only focusing on visual part.
