### ISSUE TITLE
海康21UC相机，MVS 设置 trigger on 失败

### ISSUE THREAD

**Issue by JACKLiuDay** [hku-mars/FAST-LIVO#141]
郑博您好，我在使用海康的21UC的过程中，在MVS中设置trigger mode 为 on，但是获取不到图像， trigger mode 改成 off 就可以立马获取到图像了，这是什么原因造成的呢。MID360雷达倒是同步成功了显示 GPS sync。

**Comment by JACKLiuDay** [comment]
> 郑博您好，我在使用海康的21UC的过程中，在MVS中设置trigger mode 为 on，但是获取不到图像， trigger mode 改成 off 就可以立马获取到图像了，这是什么原因造成的呢。MID360雷达倒是同步成功了显示 GPS sync。

发现问题了，相机的地线在32上接成6号线了，应该接5号线

**Comment by xuankuzcr** [comment]
是的，应该连OPTO_GND，光耦隔离的那个地，readme里面有写。我在config里设置的trigger mode是为了在无stm32时测试相机用的。
![image](https://github.com/user-attachments/assets/2ac53298-eb85-4bd4-9c80-5f7d7a96d0b2)

**Comment by JACKLiuDay** [comment]
> 是的，应该连OPTO_GND，光耦隔离的那个地，readme里面有写。我在config里设置的trigger mode是为了在无stm32时测试相机用的。 ![image](https://private-user-images.githubusercontent.com/25050620/382672068-2ac53298-eb85-4bd4-9c80-5f7d7a96d0b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTc4OTgsIm5iZiI6MTczMDcxNzU5OCwicGF0aCI6Ii8yNTA1MDYyMC8zODI2NzIwNjgtMmFjNTMyOTgtZWI4NS00YmQ0LTljODAtNWY3ZDdhOTZkMGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDEwNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZWMxMWExMjRhMzNjMDc2MzI1ZjViNzkyOTY1YTMxMzU1ZWQ0YTA1ZjVmYzE3MmJmYTVkNGE0YzY3YTQ1OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vKCGffKHd2ruShFhPHD1te6gHWhj2wu54eruykIydV8)

感谢大佬回复，郑博最近有开源FAST-LIVO2的打算吗，等三个月了:rofl:
