### ISSUE TITLE
pos_log.txt？

### ISSUE THREAD

**Issue by chenqi13814529300** [hku-mars/FAST-LIVO#145]
Why is this file empty? I really want to get some camera poses. How can I save them correctly?

**Comment by MatteoMariani99** [comment]
Uncomment the line 
dump_lio_state_to_log(fp); (line 1804)
inside laserMapping.cpp

**Comment by xuankuzcr** [comment]
Hey, I have added an interface to save the camera pose in commit dcebf84, as shown below:
https://github.com/hku-mars/FAST-LIVO/blob/dcebf84f38df004668930fbc8e2ec72ba0256000/config/avia.yaml#L17

> Why is this file empty? I really want to get some camera poses. How can I save them correctly?

**Comment by chenqi13814529300** [comment]
Boss, I'm so touched that I actually modified the code specifically for me.
