### ISSUE TITLE
关于重定位/回环方面的工作

### ISSUE THREAD

**Issue by DioBakery** [hku-mars/FAST-LIVO#146]
请问一下是否有计划进行类似于[FAST_LIO_LOCALIZATION](https://github.com/HViktorTsoi/FAST_LIO_LOCALIZATION)的涉及重定位模块工作的内容？

**Comment by xuankuzcr** [comment]
感谢关注，之后会基于livo2去加😊
ps: 可以关注下我们融合LiDAR和image测量的描述子工作 [iBTC](https://github.com/hku-mars/iBTC)。
