### ISSUE TITLE
avia.ymal参数

### ISSUE THREAD

**Issue by chenqi13814529300** [hku-mars/FAST-LIVO#147]
extrinsic_T: [ 0.04165, 0.02326, -0.0284 ] # horizon 0.05512, 0.02226, -0.0297
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

以及
    Rcl: [0.00162756,-0.999991,0.00390957,
         -0.0126748,-0.00392989,-0.999912,
          0.999918,0.00157786,-0.012681]
    Pcl: [0.0409257, 0.0318424, -0.0927219]
这些代码什么意思，是与哪个对应的外参？

**Comment by z1V-Chan** [comment]
I noticed you closed this issue when I met similar questions. Could u please share the solution or the link to it?

**Comment by chenqi13814529300** [comment]
你看下历史的issue，里面有对这个参数进行介绍


想和月亮私奔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/FAST-LIVO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月17日(星期天) 中午1:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hku-mars/FAST-LIVO] avia.ymal参数 (Issue #147)





 
I noticed you closed this issue when I met similar questions. Could u please share the solution or the link to it?
