### ISSUE TITLE
关系相机内参

### ISSUE THREAD

**Issue by chenqi13814529300** [hku-mars/FAST-LIVO#148]
roslaunch fast_livo mapping_avia.launch
rosbag play hku1.bag

为什么相机还存在畸变系数
cam_model: Pinhole
cam_width: 640
cam_height: 512
cam_fx: 431.795259219
cam_fy: 431.550090267
cam_cx: 310.833037316
cam_cy: 266.985989326
cam_d0: -0.0944205499243979
cam_d1: 0.0946727677776504
cam_d2: -0.00807970960613932
cam_d3: 8.07461209775283e-05
您好，数据集hku1.bag 里面的图像是否经过畸变矫正了？我很疑惑，我拿着这个相机内参去矫正图像的，发现图像扭曲了。

**Comment by xuankuzcr** [comment]
bag里是原始图片，畸变系数是用来给每个用到的图像patch去畸变的
