### ISSUE TITLE
some config problems

### ISSUE THREAD

**Issue by gongyue666** [hku-mars/FAST-LIVO#15]
hi, thx for your work. I want to know: 1 if transform between camera and lidar is need? where to add the R and T. 2 what is the meaning of Rcl and Pcl under 'camera':

**Comment by xuankuzcr** [comment]
Thanks for your attention~ 
1. Yes. 
2. `Rcl` represents the rotation matrix of LiDAR frame w.r.t. Camera frame.
    `Pcl` represents the translation of LiDAR frame w.r.t. Camera frame.
