### ISSUE TITLE
相机的header是173开头，雷达是159开头，相机没有读到共享内存的时间

### ISSUE THREAD

**Issue by jizhou626** [hku-mars/FAST-LIVO#150]
用的官方LIV_handhold 的雷达驱动和相机驱动包，有timeshare文件生成，雷达是avia,相机是海康MV CU013 A0UC，像素格式选的gb12packed
![Uploading 微信图片_20241115152951.jpg…]()
![Uploading wechat_2024-11-15_152753_036.png…]()

**Comment by JACKLiuDay** [comment]
https://github.com/hku-mars/FAST-LIVO/issues/142

**Comment by jizhou626** [comment]
好的，谢谢
