### ISSUE TITLE
如何避免点云被天空所染色

### ISSUE THREAD

**Issue by zzz-0930** [hku-mars/FAST-LIVO#153]
郑博您好，想请教一下再室外的情况下如何避免点云上方的部分被天空所染色呀
<img width="720" alt="bf61c48ed5eec047c592136c65b547e" src="https://github.com/user-attachments/assets/9fc3d4b9-e9fc-42f0-bef6-896117cada65">
（此处天空偏灰色）

**Comment by Es1erda** [comment]
换一个光斑比较小的激光雷达可以一定程度减轻这个问题，或尝试获取一个更为精准的外参

**Comment by xuankuzcr** [comment]
在线上色的话无法避免，因为Livox LiDAR的光斑太大了，也许可以考虑离线上色。

**Comment by G4419** [comment]
离线上色的话怎么使效果最好呢？
