### ISSUE TITLE
Vikit opencv issue under ubuntu 20.04

### ISSUE THREAD

**Issue by Atohme** [hku-mars/FAST-LIVO#16]
Hi, 
I have the following issue while compiling vikit under ubuntu 20.04

I've got the following error : 

`/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/homography.cpp: In member function ‘void vk::Homography::calcFromMatches()’:
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/homography.cpp:48:54: error: ‘RANSAC’ was not declared in this scope; did you mean ‘cv::RANSAC’?
   48 |   cv::Mat cvH = cv::findHomography(src_pts, dst_pts, RANSAC, 2./error_multiplier2);
      |                                                      ^~~~~~
      |                                                      cv::RANSAC
In file included from /usr/include/opencv4/opencv2/opencv.hpp:56,
                 from /home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/homography.cpp:13:
/usr/include/opencv4/opencv2/calib3d.hpp:230:8: note: ‘cv::RANSAC’ declared here
  230 |        RANSAC = 8, //!< RANSAC algorithm
      |        ^~~~~~
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/pinhole_camera.cpp: In member function ‘void vk::PinholeCamera::undistortImage(const cv::Mat&, cv::Mat&)’:
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/pinhole_camera.cpp:112:59: error: ‘CV_INTER_LINEAR’ was not declared in this scope
  112 |     cv::remap(raw, rectified, undist_map1_, undist_map2_, CV_INTER_LINEAR);
      |                                                           ^~~~~~~~~~~~~~~
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/img_align.cpp: In member function ‘virtual void vk::ForwardCompositionalSE3::finishIteration()’:
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/img_align.cpp:237:34: error: ‘CV_WINDOW_AUTOSIZE’ was not declared in this scope
  237 |     cv::namedWindow("residuals", CV_WINDOW_AUTOSIZE);
      |                                  ^~~~~~~~~~~~~~~~~~
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/img_align.cpp: In member function ‘virtual void vk::SecondOrderMinimisationSE3::finishIteration()’:
/home/alban/multinnov/fast_livo_ws/src/rpg_vikit/vikit_common/src/img_align.cpp:437:34: error: ‘CV_WINDOW_AUTOSIZE’ was not declared in this scope
  437 |     cv::namedWindow("residuals", CV_WINDOW_AUTOSIZE);
      |                                  ^~~~~~~~~~~~~~~~~~
make[2]: *** [rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/build.make:154 : rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/pinhole_camera.cpp.o] Erreur 1
make[2]: *** Attente des tâches non terminées....
make[2]: *** [rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/build.make:180 : rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/img_align.cpp.o] Erreur 1
make[2]: *** [rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/build.make:167 : rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/homography.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:3148 : rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/all] Erreur 2
make: *** [Makefile:141 : all] Erreur 2
Invoking "make -j12 -l12" failed
`
This error seems to appear because the newer opencv version don't use the prefix CV_, instead you have to replace it by " cv:: ".

So, for exemple the error with CV_RANSAC, I replace it by cv::RANSAC.

You can find where to do the changes in the error code.

It fixe the compile error for me.

**Comment by ceyhunblr** [comment]
https://zhuanlan.zhihu.com/p/398575632
