### ISSUE TITLE
采用硬件同步后，imu时间戳出现周期性回退

### ISSUE THREAD

**Issue by Torchmm** [hku-mars/FAST-LIVO#160]
![微信图片_20241203194056](https://github.com/user-attachments/assets/ebedce4f-2830-4962-9d84-64c79ba2db67)
采用同样的硬件同步方案，1HZ的信号地线，雷达电源地线，和采集主板地线，三个底线都共线了。频繁的周期时间戳回退现象。

**Comment by xuankuzcr** [comment]
除了确保信号地和电源地共地外，还需要使用我修改过的 livox_ros_driver 和仓库中上传的最新版本的 STM32 固件。

**Comment by xuankuzcr** [comment]
🛠️  注：仔细阅读ReadMe
