### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by strualo** [hku-mars/FAST-LIVO#18]

**Comment by xuankuzcr** [comment]
1. 首先你不能直接下结论说和LIVO结果一样，因为你用的是反射率上色，intensity作为雷达点的属性，是不像雷达和相机之间存在时差和外参的，所以你以lio下的反射率的上色结果和livo下的RGB上色结果比较是不公平的，你应该比较两者的RGB上色效果。
2. 其次这是非退化场景，结构分明纹理清晰的场景，论文里也从来没声明这种场景lio会飞掉，lio本身在这种场景就对pose有很好的优化，但由于存在外参和时差的影响，RGB上色效果不见得好。而你提到intensity和RGB效果相似，更体现了vio的优化效果。
