### ISSUE TITLE
error in hku dataset

### ISSUE THREAD

**Issue by LvXudong-HIT** [hku-mars/FAST-LIVO#19]
![Screenshot from 2022-11-17 16-00-00](https://user-images.githubusercontent.com/27817806/202389609-384e009f-1940-4c36-b841-4094356929d4.png)

**Comment by xuankuzcr** [comment]
How about trying gdb debug by modifying xxx.launch file like this 
<node pkg="fast_livo" type="fastlivo_mapping" name="laserMapping" output="screen" launch-prefix="gdb -ex run --args">

**Comment by ZZy129326999** [comment]
请问，他这个问题怎么解决啊？我也有一样的问题
