### ISSUE TITLE
Hardware time sync

### ISSUE THREAD

**Issue by Tomato1107** [hku-mars/FAST-LIVO#21]
Are there any suggestions for aligning camera and lidar timestamps？I tried two hardware sync signals, 1hz  (PPS sync) for lidar and 10hz for camera. It was found that there was a time difference.

**Comment by Tomato1107** [comment]
![nxplayer bin_4M6d2PncJ8](https://user-images.githubusercontent.com/19368992/202880946-e50151a0-6a7d-4ddb-a06c-311cc8683646.png)

**Comment by satyajitghana** [comment]
same here

**Comment by Camilochiang** [comment]
@Tomato1107, If im not wrong  what is happening, if you have a correct hardware sync,  is that you are synchronizing the start of the measurement and not when you are reciving the ROS message.  That means that the camera take significantly longer to capture the image compared with the lidar and IMU. Of course this depend of the camera that you are using, ROS package and the computer speed. Why do you want to have the messages arriving at the same time?

**Comment by Camilochiang** [comment]
You don’t need to run any algorithm to check time stamps . 
```
roscore #in one tab of terminal
rqt_graph YOURBAG.bag 
```
please run it with your bags and you will get always the same time stamps . Is your image bellow always the same bag?

**Comment by Tomato1107** [comment]
I recorded several rosbags, the time difference also seemed to be different
when I run fastlivo. It really takes some time for the camera to deal with
the image, currently I just use the 10Hz signal to trigger it.  You can
also compare different rosbags to check the results.


Camilo Chiang ***@***.***>于2022年12月2日 周五4:20写道：

**Comment by xuankuzcr** [comment]
The synchronization scheme has been updated, as mentioned in Issue #44
@Tomato1107 @Camilochiang
