### ISSUE TITLE
Hardware Time Sync Issues

### ISSUE THREAD

**Issue by satyajitghana** [hku-mars/FAST-LIVO#23]
Hi,

I tried your bag files, and tried to get the difference between the camera timestamp and the lidar timestamp. It gives exactly 0.000000000.  How is this possible? Did you modify the bag files and replace camera timestamp with lidar timestamp? Even in nanoseconds there is no difference.

**Comment by jay80253504** [comment]
same confusion

**Comment by kahowang** [comment]
same confusion

**Comment by xuankuzcr** [comment]
If you can ensure that the frame header of the camera and the LiDAR at the phisical trigger time is corresponding, you can replace the camera timestamp with the LiDAR timestamp, which eliminates the impact of network cable or usb transmission delay and ROS delay.

**Comment by xuankuzcr** [comment]
@satyajitghana @jay80253504 
The synchronization scheme has been updated, as mentioned in Issue #54
