### ISSUE TITLE
cv::Mat getImageFromMsg(const sensor_msgs::ImageConstPtr& img_msg) 中的bug

### ISSUE THREAD

**Issue by iwander-all** [hku-mars/FAST-LIVO#24]
hi, 一个小建议哦，题目中这个函数里面的cv_bridge::toCvShare最好改成cv_bridge::toCvCopy，如果照片尺寸很大的话，前者可能会出问题的。

**Comment by xuankuzcr** [comment]
测试过130w和500w像素图片，目前没有看到类似的问题。

**Comment by PengKunPROO** [comment]
right！I used 1920x1080 size of img，and got some weird wrong which lead to the program crash，and I changed it from cvshare to cvcopy，everything goes ok！
