### ISSUE TITLE
"Add 0 3D points" when testing with R3LIVE data. 

### ISSUE THREAD

**Issue by OliverShaoPT** [hku-mars/FAST-LIVO#25]
First of all, thanks for sharing your great work!
I want to test FAST-LIVO with some long bags, such as the R3LIVE datasets.
![image](https://user-images.githubusercontent.com/37506826/204472317-19aa5c83-b889-47ef-a9aa-50e780a7ce2e.png)
After adjust the parameter in yaml and launch file, "Add 0 3D points " occured.

[ INFO ]: get img at time: 1630286393.589510.
[ INFO ]: get point cloud at time: 1630286393.584056.
[ LIO ]: Raw feature num: 5325 downsamp num 4684 Map num: 11234.
[ LIO ]: Using multi-processor, used core number: 4.
[ LIO ]: time: fov_check: 0.000000 fov_check and readd: 0.000911 match: 0.002030 solve: 0.000292  ICP: 0.013996  map incre: 0.008080 total: 0.012388 icp: 0.002380 construct H: 0.000186.
[ VIO ]: Raw feature num: 5325.
**[ VIO ]: Add 0 3D points.**
[ VIO ]: time: addFromSparseMap: 0.000002 addSparseMap: 0.000274 ComputeJ: 0.000000 addObservation: 0.000001 total time: 0.000277 ave_total: 0.000277.

It seems to track raw feature successfully, but no points added. Here is my yaml and launch file.

![image](https://user-images.githubusercontent.com/37506826/204479231-fe9b2780-8ad4-47ae-afc9-c2992b8bae99.png)
![image](https://user-images.githubusercontent.com/37506826/204479361-d0b50a39-8d18-4229-85d4-f5dfc41da916.png)

Waitting for your reply.

**Comment by xuankuzcr** [comment]
The dataset in R3LIVE is not hard synchronized, so FAST-LIVO cannot run directly. You need to calculate the time offset between the camera and IMU in advance and compensate it into the system.

**Comment by OliverShaoPT** [comment]
> The dataset in R3LIVE is not hard synchronized, so FAST-LIVO cannot run directly. You need to calculate the time offset between the camera and IMU in advance and compensate it into the system.

Thanks for your reply.  After compensate the time offset, the Visual odometry and map can work. Beside the time offset issue, the camera extrinsic value of R3LIVE and FAST-LIVO can be confusing, one is camera_ext_IMU, the other is camera_to_IMU.

**Comment by xuankuzcr** [comment]
Yes, their external parameters are contrary to each other.

**Comment by Camilochiang** [comment]
@OliverShaoPT Could you please comment how did you include the time offset? Im curious. Thanks!

**Comment by PengKunPROO** [comment]
Hi, My dataset is not hard sync too,could you tell me your ways to compensate the time offset between IMU and camera? Does it need to calib or other ways to solve it?

**Comment by hr2894235132** [comment]
> > The dataset in R3LIVE is not hard synchronized, so FAST-LIVO cannot run directly. You need to calculate the time offset between the camera and IMU in advance and compensate it into the system.
> 
> Thanks for your reply. After compensate the time offset, the Visual odometry and map can work. Beside the time offset issue, the camera extrinsic value of R3LIVE and FAST-LIVO can be confusing, one is camera_ext_IMU, the other is camera_to_IMU.

Hello, can you share how you used fast-livo to run the degenerate sequence in the R3live dataset?
