### ISSUE TITLE
Questions about lense

### ISSUE THREAD

**Issue by 93won** [hku-mars/FAST-LIVO#26]
Thank you very much for sharing your great code.

I have a short question.

I'd like to build hardware like yours and run the code.

Could you tell me the model number of the camera lens used for the hardware in figure 4 of your paper?

Thank you again for sharing code and look forward to hearing from you.

**Comment by xuankuzcr** [comment]
In fact, for the cmos MV-CA013-21UC in paper, as long as it is suitable for the target size of 1/2 inch, this type of lens can be adapted. I can recommend you one  MVL-HF0628M-6MPE.

**Comment by 93won** [comment]
> 

Thank you for your reply. I will try using the lens you recommended or a similar one.
