### ISSUE TITLE
what's the meaning of "A_i" in the formula(5)?

### ISSUE THREAD

**Issue by jay80253504** [hku-mars/FAST-LIVO#27]
Hi, thanks for the great work!

when i read the paper, i'm confused the meaning of "A_i" in the formula(5). Could you teach me please?

Looking forward to your reply, thanks a lot.

**Comment by jay80253504** [comment]
I got it, A_i means affine transformation

**Comment by xuankuzcr** [comment]
Yep, A_i is the affine wrapping matrix of Q_i when projected to the corresponding image pyramid.

**Comment by xuankuzcr** [comment]
In addition, this [link](https://connecthkuhk-my.sharepoint.com/:b:/g/personal/zhengcr_connect_hku_hk/EYCLFwxE2kxPsiogcGVJ0sMB1cghU0rl5-KcriZGhcKUsg?e=fxjcF9) is the latest revised paper.
