### ISSUE TITLE
Effect of IMU Hz on performance

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/FAST-LIVO#30]
After reading the paper and downloading the rosbag, is possible to see that IMU and LiDAR synchronized eventhought the BMI088 (the imu inside LiDAR AVIA)  output values at 200 hz . Question:
- How do you think that FAST-LIVO will perform with more frequent data from the IMU sensors than the LiDAR? or it is optimal to the algorithm if they have the same Hz ?
- Additional question:  In your case, do you know what  LiVOX is doing with the IMU data when you have low frequencies outputs of LiDAR + IMU. Is it the actual value closer to your LiDAR data or is the average of X measurements corresponding to the desired frequency (i.e: Lidar 10hz = 200/10 = Average of the last 20 measurements)

Thanks in advance!

**Comment by xuankuzcr** [comment]
same in #34.
