### ISSUE TITLE
IMU question : Average?

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/FAST-LIVO#34]
Good day. Does anybody knows what the author is doing with the IMU data ? The original livox ros driver ouput either 0  or 200 HZ, meanwhile the supplied bags are sync to the same frecuency between IMU and LiDAR (and same timestamp).  You can see it  [here](https://github.com/hku-mars/FAST-LIVO/issues/21) for example

Thanks!

**Comment by xuankuzcr** [comment]
Hi, thanks for your interest. The IMU frequency in the bags tested by LIVO is about 200Hz. As for the visualization of `rqt_bag`, you should zoom in to see the IMU messages.
