### ISSUE TITLE
IMU_Processing.cpp formula error

### ISSUE THREAD

**Issue by DavidNY123** [hku-mars/FAST-LIVO#35]
Hello!
I think 
    cov_acc = cov_acc * (N - 1.0) / N + (cur_acc - mean_acc).cwiseProduct(cur_acc - mean_acc) * (N - 1.0) / (N * N);
    cov_gyr = cov_gyr * (N - 1.0) / N + (cur_gyr - mean_gyr).cwiseProduct(cur_gyr - mean_gyr) * (N - 1.0) / (N * N);
should be
    cov_acc = cov_acc * (N - 1.0) / N + (cur_acc - mean_acc).cwiseProduct(cur_acc - mean_acc) / (N-1.0);
    cov_gyr = cov_gyr * (N - 1.0) / N + (cur_gyr - mean_gyr).cwiseProduct(cur_gyr - mean_gyr) / (N-1.0);

I don't know if there is something wrong with the formula I derived,I have been having this problem since FASTLIO1.0 and 2.0

**Comment by xuankuzcr** [comment]
I have checked and tested the recursive variance formula carefully, and it seems no problem. You can follow this [link](https://blog.csdn.net/FrankieHello/article/details/89358530) to get the derivation process of flow data variance.
