### ISSUE TITLE
[laserMapping-1] process has died [pid 31651, exit code -11

### ISSUE THREAD

**Issue by crowningwang** [hku-mars/FAST-LIVO#40]
尊敬的港大团队，您好
在编译完成之后运行roslaunch fast_livo mapping_avia.launch后laserMapping中断，并且播放数据集rviz没有显示，请问应该如何解决这个问题，我的配置如下：
Ubuntu->18.04
PCL->1.9.1
Eigen->3.4.0
OpenCV->4.2.0
![2023-01-28 23-16-39屏幕截图](https://user-images.githubusercontent.com/114406126/215274793-44e3c567-3414-4de8-bd88-ae50a6e76bd3.png)

**Comment by crowningwang** [comment]
![2023-01-28 23-25-51屏幕截图](https://user-images.githubusercontent.com/114406126/215274863-5be1caa6-642a-416e-8770-17ce0cd10611.png)

**Comment by IaroslavS** [comment]
> ![2023-01-28 23-25-51屏幕截图](https://user-images.githubusercontent.com/114406126/215274863-5be1caa6-642a-416e-8770-17ce0cd10611.png)

How did you solve this problem ?

**Comment by xuankuzcr** [comment]
你用gdb看一下哪行报错了，opencv推荐3.x的版本

**Comment by justleap** [comment]
请问这个问题是怎么解决的，遇到同样的问题，rviz有时不显示有时可以，跑的时候会出现进程崩溃

**Comment by autumntang** [comment]
Error: RuntimeError: xioctl(VIDIOC_S_FMT) failed, errno=5 Last Error: Input/output error
