### ISSUE TITLE
[laserMapping-1] process has died [pid 11250, exit code -11

### ISSUE THREAD

**Issue by IaroslavS** [hku-mars/FAST-LIVO#41]
If anybody faces this kind of error (look at the screen shot), please  pay attention to string 
```
printf("[ LIO ]: Using multi-processor, used core number: %s.\n", MP_PROC_NUM);
```
in laserMapping.cpp

Resolve the bug by changing the above string to the following:
```
printf("[ LIO ]: Using multi-processor, used core number: %d.\n", MP_PROC_NUM);
```

![Screenshot from 2023-02-01 12-31-57](https://user-images.githubusercontent.com/47471352/216623360-3cc37698-b5dc-4dde-93e8-81d475027401.png)

**Comment by sebastiantorres1** [comment]
I had made a research in the lasermappin.cpp code and apparently the process stops working in this part of the code: 

` if(!vk::camera_loader::loadFromRosNs("laserMapping", lidar_selector->cam))`
`      throw std::runtime_error("Camera model not correctly specified."); `

Have you faced this problem?

I tried your solution and it doesn't fix my problem.

**Comment by IaroslavS** [comment]
> vk::camera_loader::loadFromRosNs("laserMapping", lidar_selector->cam

Yes, I faced similiar problem, check out config file that you use when launching, for example this config file
https://github.com/hku-mars/FAST-LIVO/blob/main/config/camera_NTU_VIRAL.yaml#L1
has field `cam_model` which should be one of the set {Ocam, Pinhole, ATAN}

Check or edit this file 
https://github.com/uzh-rpg/rpg_vikit/blob/master/vikit_ros/include/vikit/camera_loader.h
that repository (https://github.com/uzh-rpg/rpg_vikit/) is a submodule for fast-livo

**Comment by sebastiantorres1** [comment]
Apparently i just have to change the camera model "Pinhole" to "ATAN" in the configuration, but now it only shows the camera and the trajectory, but not the lidar odometry in the rviz  like this image shows

![Screenshot from 2023-02-06 10-07-11](https://user-images.githubusercontent.com/123670540/217007929-c020aeb4-19ec-4dc0-b472-dbe00915e163.png)

How did you solve this?

**Comment by xuankuzcr** [comment]
As for our provided bags, you should use `Pinhole` camera model. While running your own collected dataset, choose the camera model according to your device.
