### ISSUE TITLE
question about ImuProcess::UndistortPcl()

### ISSUE THREAD

**Issue by zzwu29** [hku-mars/FAST-LIVO#43]
Dear Authors:
Thank you for contributing elegant programs to open-source SLAM, which helped me a lot in my learning. During this process, I have a question about **ImuProcess::UndistortPcl()**
https://github.com/hku-mars/FAST-LIVO/blob/a8918c23dc4dba7d98fa723a9fa0fc2cbdf4d977/src/IMU_Processing.cpp#L808-L811
From my point of view, the fast-livo code corresponds to the following formula
![image](https://user-images.githubusercontent.com/44901540/218631711-3fe0047c-84c4-42e1-a385-d2ebc383fa5b.png)
Does it use the extrinsic rotation of Lidar and IMU? Please help check whether the following formula is correct
![image](https://user-images.githubusercontent.com/44901540/218631765-087f405e-fd85-4225-9573-a1865cf7f9fb.png)
R is the direction cosine matrix, p is the translation, L is lidar frame, G is global frame, and b is IMU frame.
Wish you all the best!

**Comment by xuankuzcr** [comment]
In the `T_ei`, `e` is in the IMU frame, and `i` is in the LiDAR frame. Therefore, the extrinsic LiDAR frame w.r.t. IMU frame is used only once.

**Comment by zzwu29** [comment]
您好，您的邮件我已经收到，会尽快阅读并回复！
                                                                               zzWu

**Comment by zzwu29** [comment]
Please forgive my trouble, the translation of lidar w.r.t. IMU is Lid_ offset_ to_ IMU, while the rotation is expressed as Lid_ rot_ to_ IMU, right? When will the extrinsic rotation parameter of lidar w.r.t. IMU be used?
