### ISSUE TITLE
Question about cmakefile

### ISSUE THREAD

**Issue by ToutDonner** [hku-mars/FAST-LIVO#44]
https://github.com/hku-mars/FAST-LIVO/blob/a8918c23dc4dba7d98fa723a9fa0fc2cbdf4d977/CMakeLists.txt#L30

这里是不是应该去掉引号啊，4核心编译时宏定义核心数量为const char* 去掉引号才能通过

**Comment by xuankuzcr** [comment]
参考这个[link](https://github.com/hku-mars/FAST_LIO/blob/02d022e3164cc39afdc56618a056bbaac9aa4d57/CMakeLists.txt#L25)，应该去掉，要不然有的电脑环境可能报错。

**Comment by ToutDonner** [comment]
> 参考这个[link](https://github.com/hku-mars/FAST_LIO/blob/02d022e3164cc39afdc56618a056bbaac9aa4d57/CMakeLists.txt#L25)，应该去掉，要不然有的电脑环境可能报错。

Thinks！
love from china❤️
