### ISSUE TITLE
请问一下关于相机参数设置方面的 问题

### ISSUE THREAD

**Issue by Ningningwang11** [hku-mars/FAST-LIVO#45]
首先我使用hku1.bag的包是可以正常运行fast-livo
但是我换了自己的设备：主机（jetson agx xavier）、livox-mid70、imu(wheeltec)、ZED2。
这是我遇到的问题
![2023-02-15 17-21-00屏幕截图](https://user-images.githubusercontent.com/112852842/218988399-164f882d-5adc-431d-9dd4-7d1fc84b3853.png)
为了排除雷达和imu是不是跑的通fast-lio我把img_enable设置为0后又跑了一下程序，发现rviz虽然没有点云图，但是看样子应该是跑的了fast-lio的，
![2023-02-15 17-21-56屏幕截图](https://user-images.githubusercontent.com/112852842/218988875-27dae79c-538e-4671-9de2-83dc8780cbc6.png)
。所以我觉得可能是相机标定信息什么的设置不对。
基于相机的出厂标定信息修改了下面的部分
![2023-02-15 17-24-55屏幕截图](https://user-images.githubusercontent.com/112852842/218989598-09019a56-da37-48d5-9a43-68ae397241c0.png)

我对这一块刚入门，想请教一下，我都需要改哪些参数，才可以像跑hku1.bag一样基于我的设备跑通fast-livo。 非常感谢！

**Comment by Ningningwang11** [comment]
修改了

**Comment by Ningningwang11** [comment]
cam_width:   640 #672  # 640
cam_height:  360 #376    #512
原来是图片分辨率需要调

**Comment by Aokiji996** [comment]
我的设备跟你几乎一样，我用的zed内置的imu，能看看你的config文件吗

**Comment by Ningningwang11** [comment]
现在单跑fastlio2感觉效果很不错，但是跑fastlivo后虽然能跑，效果有点差。但是雷达-imu，相机-雷达都标定了，还是跑的远没有他原版数据包效果好。甚至说效果有些差。明天我去翻一下那个文件给你，感觉仅供参考了，如果明天中午12点前我没有发的话，请在提醒我一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aokiji996 ***@***.***&gt;
发送时间: 2023年4月5日 23:46
收件人: hku-mars/FAST-LIVO ***@***.***&gt;
抄送: Ningningwang11 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [hku-mars/FAST-LIVO] 请问一下关于相机参数设置方面的 问题 (Issue #45)





 
我的设备跟你几乎一样，我用的zed内置的imu，能看看你的config文件吗

**Comment by Aokiji996** [comment]
太感谢了

**Comment by Ningningwang11** [comment]
zed内参 我用的是原厂数据，雷达-imu标定，相机-雷达标定的包都可以在github上找到。
我最终跑的效果有点差，如果您最终跑通的效果比较好，点云上色效果比较准确，定位比较准确的话，还请回复我您觉得的关键操作细节，多谢。






898074006
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/FAST-LIVO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 凌晨0:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hku-mars/FAST-LIVO] 请问一下关于相机参数设置方面的 问题 (Issue #45)





 
太感谢了

**Comment by Aokiji996** [comment]
我的mid70获取数据之后的时间戳似乎有些问题，我怀疑这是导致我不能跑通的原因，但我不知道要怎么才能正确的设置这个时间戳
![image](https://user-images.githubusercontent.com/109837545/230372342-cee8c203-c341-489d-8bca-50b3274ea1cc.png)

**Comment by Ningningwang11** [comment]
我的笔记里有ptcd什么的你查一下





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aokiji996 ***@***.***&gt;
发送时间: 2023年4月6日 19:58
收件人: hku-mars/FAST-LIVO ***@***.***&gt;
抄送: Ningningwang11 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [hku-mars/FAST-LIVO] 请问一下关于相机参数设置方面的 问题 (Issue #45)

**Comment by Ningningwang11** [comment]
加个微信，
QQ898974006

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aokiji996 ***@***.***&gt;
发送时间: 2023年4月6日 19:58
收件人: hku-mars/FAST-LIVO ***@***.***&gt;
抄送: Ningningwang11 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [hku-mars/FAST-LIVO] 请问一下关于相机参数设置方面的 问题 (Issue #45)

**Comment by Ningningwang11** [comment]
尬住了，我QQ 打错了
898074006



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Aokiji996 ***@***.***&gt;
发送时间: 2023年4月6日 20:08
收件人: hku-mars/FAST-LIVO ***@***.***&gt;
抄送: Ningningwang11 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [hku-mars/FAST-LIVO] 请问一下关于相机参数设置方面的 问题 (Issue #45)





 
我已经添加了你的QQ，收到了吗
