### ISSUE TITLE
光度误差雅克比中是否考虑了相机的畸变参数？

### ISSUE THREAD

**Issue by Cc19245** [hku-mars/FAST-LIVO#52]
你好chunran @xuankuzcr ，感谢你优秀的开源工作！

目前我在学习FAST-LIVO的代码，我发现在 [相机投影过程中](https://github.com/hku-mars/FAST-LIVO/blob/main/src/lidar_selection.cpp#L811) 考虑了畸变，但是在 [光度对齐的地方](https://github.com/hku-mars/FAST-LIVO/blob/main/src/lidar_selection.cpp#L814) 并没有考虑畸变，而是直接用无畸变的Pinhole相机模型计算雅克比。请问是有什么特殊的考虑吗？或者是我没有看仔细漏掉了一些内容？

期待你的回复，谢谢！

**Comment by xuankuzcr** [comment]
没考虑，因为针孔相机畸变很小可以忽略不计，但是在residual计算时考虑了。如果对于畸变比较大的鱼眼相机，你觉得考虑畸变的雅克比相对于不考虑的收敛速度会更快么？

**Comment by Cc19245** [comment]
> 

不考虑畸变的雅克比的话，是否会对优化结果有影响呢？因为不考虑畸变部分的雅克比是不准确的。我也不是很确定到底对速度和精度有什么影响，感觉又好像影响都不大？
