### ISSUE TITLE
When using spinning lidar, point clouds outside the camera's field of view were also colored.

### ISSUE THREAD

**Issue by fy99925** [hku-mars/FAST-LIVO#60]
When spinning lidar was used for testing, it was found that not only visible area point clouds were registered but also invisible point clouds directly behind. I noticed that in NTU-VIRAL dataset also exists this problem. I don't know how to solve it. 
![Screenshot 2023-03-27 10:40:18](https://user-images.githubusercontent.com/77228847/227828578-9de940e0-eabb-4f56-96b1-e9586a009616.png)

**Comment by xuankuzcr** [comment]
https://github.com/hku-mars/FAST-LIVO/blob/a8918c23dc4dba7d98fa723a9fa0fc2cbdf4d977/src/laserMapping.cpp#L730
You can add `V3D pf(lidar_selector->new_frame_->w2f(p_w)); if(pf[2]<0) continue;`  after this line.
