### ISSUE TITLE
运行Velodyne16线数据问题

### ISSUE THREAD

**Issue by zzwu29** [hku-mars/FAST-LIVO#63]
您好，最近使用FAST-LIVO时，使用了一个Velodyne16线的数据集，遇到问题向请教您
其在FAST-LIO上运行正常，但FAST-LIVO运行数秒后报错，截图如下，是什么原因呢？
![image](https://user-images.githubusercontent.com/44901540/232512046-2fd04009-ecb1-4319-a6bc-e13d2dd251b1.png)

**Comment by BUG423** [comment]
你好，我遇到了相同的问题，请问您是否有解决方案？不胜感激！

**Comment by zzwu29** [comment]
> 你好，我遇到了相同的问题，请问您是否有解决方案？不胜感激！

可以参考FAST-LIO的handler部分

**Comment by BUG423** [comment]
您好，我已经收到您的来信，非常感谢！

**Comment by seanXMU** [comment]
> > 你好，我遇到了相同的问题，请问您是否有解决方案？不胜感激！
> 
> 可以参考FAST-LIO的handler部分
请问具体怎么解决呢？可以运行kitti数据集吗

**Comment by BUG423** [comment]
您好，我已经收到您的来信，非常感谢！祝好！

**Comment by seanXMU** [comment]
可以参考FAST-LIO的handler部分
请问具体怎么解决呢？可以运行kitti数据集吗
