### ISSUE TITLE
关于VIRAL数据集精度问题。

### ISSUE THREAD

**Issue by h-k8888** [hku-mars/FAST-LIVO#65]
你好，我用VIRAL数据集测试了FastLIO2和Fast-LIVO，用的是Fast-LIVO默认的配置，测试结果FastLIO2精度都高于Fast-LIVO，这与paper里的结果不太相符。
请问这是配置参数的原因吗？

**Comment by xuankuzcr** [comment]
1. FAST-LIO2仓库的代码版本在不断更新，论文中使用的是2021.10月份左右的版本，因为LIVO在NTU数据集上提升不大（由于画质问题），LIO方面一点小的改动就会对实验结果产生差异。
2. NTU数据集LiDAR的消息用的是帧末时间，实际使用时应该减0.1s。
3. 在图像质量不好的数据集中，建议提升img_point_cov，更相信LiDAR的观测。
