### ISSUE TITLE
Trouble a camera image in RViz.

### ISSUE THREAD

**Issue by Nationarity** [hku-mars/FAST-LIVO#67]
I am afraid this is a rudimentary question,

roslaunch livox_ros_driver livox_lidar_msg.launch
I am having trouble getting a camera image in RViz.

but the image can be displayed in usb_cam-usb_cam-test.launch.

I would like to know the cause and solition.

![Screenshot from 2023-06-21 13-57-12](https://github.com/hku-mars/FAST-LIVO/assets/53669673/c8698642-798b-4ff9-8f99-d336813899c4)
![Screenshot from 2023-06-21 14-20-31](https://github.com/hku-mars/FAST-LIVO/assets/53669673/2b062353-82c4-4976-a2f2-d83e431e3c80)

**Comment by 85256638** [comment]
@Nationarity can you let us know how you solved this issue please?
