### ISSUE TITLE
Covariance values

### ISSUE THREAD

**Issue by karansspk** [hku-mars/FAST-LIVO#68]
In avia_resize.yaml file there are some parameters:
img_point_cov
laser_point_cov

acc_cov_scale
gyr_cov_scale
Can you please tell what are these parameters and their significance?
Also plz add how can we get these values from sensors?

**Comment by xuankuzcr** [comment]
photometric error cov
point-to-plane residual cov
acc measurement cov
gyr measurement cov
These values are generally empirical values of the same order of magnitude as their actual physical meaning.
