### ISSUE TITLE
Any news for releasing codes?

### ISSUE THREAD

**Issue by LangDaoAI** [hku-mars/FAST-LIVO#7]
Hi Team,

Any news for releasing codes?

![image](https://user-images.githubusercontent.com/83859417/177070908-cc933832-6c6b-4be1-a43c-3c2bb6de91eb.png)

Thanks!

**Comment by sp1keCHEN** [comment]
+1

**Comment by Minzhao1995** [comment]
waiting +1

**Comment by FSRyan** [comment]
+10010

**Comment by Minamiyama** [comment]
+65536

**Comment by yxllnSLAM** [comment]
+1

**Comment by seajayshore** [comment]
+4294967296

**Comment by hr2894235132** [comment]
+100000000000

**Comment by xuankuzcr** [comment]
We've already opened the source code, guys. 
Thanks for your attention, tears in the eyes.

**Comment by Camilochiang** [comment]
> We've already opened the source code, guys. Thanks for your attention, tears in the eyes.

Thanks ;) Took a while, but is done! congrats ;)
