### ISSUE TITLE
请问PWM使能avia激光雷达采集数据问题？

### ISSUE THREAD

**Issue by rainlord2** [hku-mars/FAST-LIVO#73]
您好，请问一下，STM32 PWM输出应该如何连接avia激光雷达，才能通过PWM使能激光雷达进行数据采集。PWM的高电平的电压需要多少伏？

**Comment by xuankuzcr** [comment]
通过sync port给pps signal，然后通过一个TTL转USB给time signal (GPRMC)。大于等于3.3v就行。
