### ISSUE TITLE
GPRMC信号是必要的吗

### ISSUE THREAD

**Issue by WangShiJieAOTM** [hku-mars/FAST-LIVO#75]
GPRMC信号是必要的吗

**Comment by WangShiJieAOTM** [comment]
我现在正在尝试使用禾赛雷达运行FAST-LIVO，我应该怎么同步呢？我目前使用了stm32f1作为相机和雷达的时钟，雷达接上了PPS信号

**Comment by xuankuzcr** [comment]
stm32可以模拟GPRMC信号给出去

**Comment by WangShiJieAOTM** [comment]
> stm32可以模拟GPRMC信号给出去
这部分在[Handheld_ws]中开源了吗，模拟的信号时间戳是固定的吗时间是从哪里来的

**Comment by xuankuzcr** [comment]
这部分没开源，之前没有考虑这件事，之后会在别的项目中开源。时间是随意起始点的整数倍0.1秒时间戳。

**Comment by xuankuzcr** [comment]
不确定没这么测试过

**Comment by MisEty** [comment]
> > 这部分没有开源，之前没有考虑这件事，之后会在其他项目中开源。时间是首先启动点的整数倍0.1秒。
> 
> 我使用PC外接一个USB-232模块定时将PC时间转为GPRMC信号给雷达，这个方案是可行的吗，有什么需要注意的呢？

您好，请问您GPRMC信号的问题解决了吗
