### ISSUE TITLE
关于相机雷达联合标定的问题

### ISSUE THREAD

**Issue by WangShiJieAOTM** [hku-mars/FAST-LIVO#79]
想请教一下作者，对于机械旋转雷达和相机联合标定外参使用的方法

**Comment by xuankuzcr** [comment]
推荐这个仓库 https://github.com/koide3/direct_visual_lidar_calibration
最近在用，非常鲁棒

**Comment by WangShiJieAOTM** [comment]
感谢回复，我去看看
