### ISSUE TITLE
Compiling FAST-LIVO on 22.04

### ISSUE THREAD

**Issue by arihantlunawat** [hku-mars/FAST-LIVO#81]
I am having several issues compiling FAST-LIVO on 22.04. I know this is not officially supported but I am curious to know if anyone has tried to compile it and has been successful. Currently the compilation errors can be summarized as below,
- OpenCV 3 -> OpenCV 4 breaking changes, for example `CV_INTER_LINEAR` -> `cv::INTER_LINEAR`
- Sophus changing to header only library, double is no longer the default type, you have to specify a template parameter for every declaration of Sophus::SE3.
- ROS is no longer supported so had to work around it

**Comment by zhongwei1122** [comment]
> I am having several issues compiling FAST-LIVO on 22.04. I know this is not officially supported but I am curious to know if anyone has tried to compile it and has been successful. Currently the compilation errors can be summarized as below,
> 
> * OpenCV 3 -> OpenCV 4 breaking changes, for example `CV_INTER_LINEAR` -> `cv::INTER_LINEAR`
> * Sophus changing to header only library, double is no longer the default type, you have to specify a template parameter for every declaration of Sophus::SE3.
> * ROS is no longer supported so had to work around it

Hello, may I ask if you have successfully compiled and run the FAST-LIVO algorithm in ROS2？I am trying to do this work.

**Comment by wtwdwr123** [comment]
> > I am having several issues compiling FAST-LIVO on 22.04. I know this is not officially supported but I am curious to know if anyone has tried to compile it and has been successful. Currently the compilation errors can be summarized as below,
> > 
> > * OpenCV 3 -> OpenCV 4 breaking changes, for example `CV_INTER_LINEAR` -> `cv::INTER_LINEAR`
> > * Sophus changing to header only library, double is no longer the default type, you have to specify a template parameter for every declaration of Sophus::SE3.
> > * ROS is no longer supported so had to work around it
> 
> Hello, may I ask if you have successfully compiled and run the FAST-LIVO algorithm in ROS2？I am trying to do this work.

你成功了么？用ros2编译fast-livo
