### ISSUE TITLE
Crops and Overlays an upper corner - Fast-Livo with VLP16 and Zed2

### ISSUE THREAD

**Issue by sumedhfb** [hku-mars/FAST-LIVO#91]
Hi,
I am using FAST-LIVO with a Velodyne VLP-16 and a ZED2 Camera. I followed [13](https://github.com/hku-mars/FAST-LIVO/issues/13#issuecomment-1314167250) to set it up on config in avia_resize.yaml, and used the ZED values to set up camera parameters in camera_pinhole_resize.yaml. However, the overlayed point cloud is restricted to the left corner of the image instead of the front of the camera. The intrinsic and extrinsic measurements are accurate .

![image](https://github.com/hku-mars/FAST-LIVO/assets/143547297/cded8f6c-6d5c-4b30-b5ea-1d1a93ebc2b4)
The white pointcloud is a part of the original that it crops and overlays onto the image.
I am lost on options to change - am I missing something?

**Comment by xuankuzcr** [comment]
Please check the coordinate system definition of the extrinsic parameters.
