### ISSUE TITLE
No such file or directory  #include <fast_livo/States.h>

### ISSUE THREAD

**Issue by QXFGR** [hku-mars/FAST-LIVO#92]
when i use 'catkin_make' ,it displays this ,how can i solve it?

**Comment by riteshsharmamst** [comment]
I am getting the same error. Were you able to solve this issue?

**Comment by QXFGR** [comment]
i am sorry to reply late, i think this is because different thread compile different files and some file need fast,so you can add -j8 to compile success ,or compile multiple times.And below is the picture.

---Original---
From: ***@***.***&gt;
Date: Wed, May 22, 2024 07:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hku-mars/FAST-LIVO] No such file or directory  #include<fast_livo/States.h&gt; (Issue #92)




 
I am getting the same error. Were you able to solve this issue?
