### ISSUE TITLE
corrupted size vs. prev_size [laserMapping-2] process has died

### ISSUE THREAD

**Issue by jiananzuiren** [hku-mars/FAST-LIVO#93]
![2024-04-09 16-17-00屏幕截图](https://github.com/hku-mars/FAST-LIVO/assets/104779198/e7bf6ad4-8307-4c4b-aa19-b9455a7b7897)
When I was using the dataset provided by FAST-LIVO, I encountered this error

**Comment by xuankuzcr** [comment]
You can use gdb to get some debug info and check your dependency versions.

**Comment by jiananzuiren** [comment]
您好，QXN已经收到您的邮件，感谢您的来件
