### ISSUE TITLE
error when running your dataset

### ISSUE THREAD

**Issue by xuxumiao777** [hku-mars/FAST-LIVO#95]
roslaunch fast_livo mapping_avia.launch
... logging to /home/xuxumiao/.ros/log/2738f926-0f71-11ef-8596-11d7ee4afbb7/roslaunch-rog-9128.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rog:33955/

SUMMARY
========

PARAMETERS
 * /cam_cx: 318.908851
 * /cam_cy: 234.238189
 * /cam_fx: 453.483063
 * /cam_fy: 453.254913
 * /camera/Pcl: [0.0409257, 0.031...
 * /camera/Rcl: [0.00162756, -0.9...
 * /camera/img_topic: /left_camera/image
 * /common/imu_topic: /livox/imu
 * /common/lid_topic: /livox/lidar
 * /cube_side_length: 20
 * /debug: 0
 * /dense_map_enable: 1
 * /feature_extract_enable: 0
 * /filter_size_map: 0.3
 * /filter_size_surf: 0.15
 * /grid_size: 40
 * /img_enable: 1
 * /img_point_cov: 100
 * /laserMapping/cam_cx: 310.833037316
 * /laserMapping/cam_cy: 266.985989326
 * /laserMapping/cam_d0: -0.0944205499243979
 * /laserMapping/cam_d1: 0.0946727677776504
 * /laserMapping/cam_d2: -0.00807970960613932
 * /laserMapping/cam_d3: 8.07461209775283e-05
 * /laserMapping/cam_fx: 431.795259219
 * /laserMapping/cam_fy: 431.550090267
 * /laserMapping/cam_height: 512
 * /laserMapping/cam_model: Pinhole
 * /laserMapping/cam_width: 640
 * /laser_point_cov: 0.001
 * /lidar_enable: 1
 * /mapping/acc_cov_scale: 100
 * /mapping/extrinsic_R: [1, 0, 0, 0, 1, 0...
 * /mapping/extrinsic_T: [0.04165, 0.02326...
 * /mapping/fov_degree: 90
 * /mapping/gyr_cov_scale: 10000
 * /max_iteration: 10
 * /ncc_en: False
 * /ncc_thre: 0
 * /outlier_threshold: 300
 * /patch_size: 8
 * /point_filter_num: 2
 * /preprocess/blind: 5
 * /preprocess/lidar_type: 1
 * /preprocess/scan_line: 6
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    laserMapping (fast_livo/fastlivo_mapping)
    republish (image_transport/republish)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [9136]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 2738f926-0f71-11ef-8596-11d7ee4afbb7
process[rosout-1]: started with pid [9146]
started core service [/rosout]
process[laserMapping-2]: started with pid [9153]
process[rviz-3]: started with pid [9154]
process[republish-4]: started with pid [9155]
Multi thread started 
debug:0 MIN_IMG_COUNT: 1000
[ INFO] [1715416414.118077360]: Found parameter: laserMapping/cam_model, value: Pinhole
[ INFO] [1715416414.118623722]: Found parameter: laserMapping/cam_width, value: 640
[ INFO] [1715416414.118778407]: Found parameter: laserMapping/cam_height, value: 512
[ INFO] [1715416414.118937226]: Found parameter: laserMapping/cam_fx, value: 431.795
[ INFO] [1715416414.119085660]: Found parameter: laserMapping/cam_fy, value: 431.55
[ INFO] [1715416414.119216617]: Found parameter: laserMapping/cam_cx, value: 310.833
[ INFO] [1715416414.119335700]: Found parameter: laserMapping/cam_cy, value: 266.986
[ INFO] [1715416414.119455967]: Found parameter: laserMapping/cam_d0, value: -0.0944205
[ INFO] [1715416414.119578108]: Found parameter: laserMapping/cam_d1, value: 0.0946728
[ INFO] [1715416414.119710539]: Found parameter: laserMapping/cam_d2, value: -0.00807971
[ INFO] [1715416414.119854914]: Found parameter: laserMapping/cam_d3, value: 8.07461e-05
[ INFO ]: get point cloud at time: 1577836978.699827.
[ INFO ]: get img at time: 1577836978.699827.
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836978.799653.
[ INFO ]: get img at time: 1577836978.799653.
[ INFO] [1715416424.098361639]: IMU Initializing: 0.5 %
[ WARN] [1715416424.098402299]: Reset ImuProcess
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836978.899480.
[ INFO ]: get img at time: 1577836978.899480.
[ INFO] [1715416424.197875977]: IMU Initializing: 10.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836978.999310.
[ INFO ]: get img at time: 1577836978.999310.
[ INFO] [1715416424.297557771]: IMU Initializing: 20.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.099941.
[ INFO ]: get img at time: 1577836979.099941.
[ INFO] [1715416424.396768280]: IMU Initializing: 31.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.199771.
[ INFO ]: get img at time: 1577836979.199771.
[ INFO] [1715416424.497483387]: IMU Initializing: 41.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.299606.
[ INFO ]: get img at time: 1577836979.299606.
[ INFO] [1715416424.597653312]: IMU Initializing: 51.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.399457.
[ INFO ]: get img at time: 1577836979.399457.
[ INFO] [1715416424.697026123]: IMU Initializing: 61.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.499283.
[ INFO ]: get img at time: 1577836979.499283.
[ INFO] [1715416424.795842825]: IMU Initializing: 71.5 %
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.599930.
[ INFO ]: get img at time: 1577836979.599930.
[ INFO] [1715416424.896067917]: IMU Initializing: 81.5 %
FAST-LIO not ready
[ INFO] [1715416424.896374312]: IMU Initializing: 92.5 %
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.699775.
[ INFO ]: get img at time: 1577836979.699775.
[ INFO] [1715416424.996777721]: IMU Initializing: 93.0 %
[ INFO] [1715416424.996812787]: IMU Initials: Gravity: -0.2714 -0.4027 -9.7980 0.9939; state.bias_g: 100.0000 100.0000 100.0000; acc covarience: 0.00111717 0.00062000 0.00097596; gry covarience: 0.00000725 0.00000545 0.00000694
[ INFO] [1715416424.996835888]: IMU Initials: Gravity: -0.2714 -0.4027 -9.7980 0.9939; state.bias_g: 0.0000 0.0000 0.0000; acc covarience: 0.11171720 0.06200038 0.09759611; gry covarience: 0.07248070 0.05450585 0.06941470
FAST-LIO not ready
FAST-LIO not ready
[ INFO ]: get point cloud at time: 1577836979.799607.
[ INFO ]: get img at time: 1577836979.799607.
[ VIO ]: Raw feature num: 0.
[ VIO ]: Add 0 3D points.
[ VIO ]: time: addFromSparseMap: 0.000002 addSparseMap: 0.000012 ComputeJ: 0.000001 addObservation: 0.000001 total time: 0.000017 ave_total: 8905.256738.
[ INFO ]: get point cloud at time: 1577836979.899443.
[ INFO ]: get img at time: 1577836979.899443.
[ LIO ]: Raw feature num: 6435 downsamp num 4165 Map num: 2860.
[ LIO ]: Using multi-processor, used core number: 4.
[ LIO ]: time: fov_check: 0.000000 fov_check and readd: 0.001892 match: 0.000000 solve: 0.000000  ICP: 0.000250  map incre: 0.005021 total: 0.007164 icp: 0.000143 construct H: 0.000000.
[ VIO ]: Raw feature num: 6435.
[ VIO ]: Add 98 3D points.
[ VIO ]: time: addFromSparseMap: 0.000001 addSparseMap: 0.001206 ComputeJ: 0.000000 addObservation: 0.000000 total time: 0.001207 ave_total: 8905.361562.
[laserMapping-2] process has died [pid 9153, exit code -11, cmd /home/xuxumiao/catkin_ws/devel/lib/fast_livo/fastlivo_mapping __name:=laserMapping __log:=/home/xuxumiao/.ros/log/2738f926-0f71-11ef-8596-11d7ee4afbb7/laserMapping-2.log].
log file: /home/xuxumiao/.ros/log/2738f926-0f71-11ef-8596-11d7ee4afbb7/laserMapping-2*.log

**Comment by yahyahajla** [comment]
> roslaunch fast_livo mapping_avia.launch ... logging to /home/xuxumiao/.ros/log/2738f926-0f71-11ef-8596-11d7ee4afbb7/roslaunch-rog-9128.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://rog:33955/
> # SUMMARY
> 
> PARAMETERS
> 
>     * /cam_cx: 318.908851
> 
>     * /cam_cy: 234.238189
> 
>     * /cam_fx: 453.483063
> 
>     * /cam_fy: 453.254913
> 
>     * /camera/Pcl: [0.0409257, 0.031...
> 
>     * /camera/Rcl: [0.00162756, -0.9...
> 
>     * /camera/img_topic: /left_camera/image
> 
>     * /common/imu_topic: /livox/imu
> 
>     * /common/lid_topic: /livox/lidar
> 
>     * /cube_side_length: 20
> 
>     * /debug: 0
> 
>     * /dense_map_enable: 1
> 
>     * /feature_extract_enable: 0
> 
>     * /filter_size_map: 0.3
> 
>     * /filter_size_surf: 0.15
> 
>     * /grid_size: 40
> 
>     * /img_enable: 1
> 
>     * /img_point_cov: 100
> 
>     * /laserMapping/cam_cx: 310.833037316
> 
>     * /laserMapping/cam_cy: 266.985989326
> 
>     * /laserMapping/cam_d0: -0.0944205499243979
> 
>     * /laserMapping/cam_d1: 0.0946727677776504
> 
>     * /laserMapping/cam_d2: -0.00807970960613932
> 
>     * /laserMapping/cam_d3: 8.07461209775283e-05
> 
>     * /laserMapping/cam_fx: 431.795259219
> 
>     * /laserMapping/cam_fy: 431.550090267
> 
>     * /laserMapping/cam_height: 512
> 
>     * /laserMapping/cam_model: Pinhole
> 
>     * /laserMapping/cam_width: 640
> 
>     * /laser_point_cov: 0.001
> 
>     * /lidar_enable: 1
> 
>     * /mapping/acc_cov_scale: 100
> 
>     * /mapping/extrinsic_R: [1, 0, 0, 0, 1, 0...
> 
>     * /mapping/extrinsic_T: [0.04165, 0.02326...
> 
>     * /mapping/fov_degree: 90
> 
>     * /mapping/gyr_cov_scale: 10000
> 
>     * /max_iteration: 10
> 
>     * /ncc_en: False
> 
>     * /ncc_thre: 0
> 
>     * /outlier_threshold: 300
> 
>     * /patch_size: 8
> 
>     * /point_filter_num: 2
> 
>     * /preprocess/blind: 5
> 
>     * /preprocess/lidar_type: 1
> 
>     * /preprocess/scan_line: 6
> 
>     * /rosdistro: noetic
> 
>     * /rosversion: 1.16.0
> 
> 
> NODES / laserMapping (fast_livo/fastlivo_mapping) republish (image_transport/republish) rviz (rviz/rviz)
> 
> auto-starting new master process[master]: started with pid [9136] ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 2738f926-0f71-11ef-8596-11d7ee4afbb7 process[rosout-1]: started with pid [9146] started core service [/rosout] process[laserMapping-2]: started with pid [9153] process[rviz-3]: started with pid [9154] process[republish-4]: started with pid [9155] Multi thread started debug:0 MIN_IMG_COUNT: 1000 [ INFO] [1715416414.118077360]: Found parameter: laserMapping/cam_model, value: Pinhole [ INFO] [1715416414.118623722]: Found parameter: laserMapping/cam_width, value: 640 [ INFO] [1715416414.118778407]: Found parameter: laserMapping/cam_height, value: 512 [ INFO] [1715416414.118937226]: Found parameter: laserMapping/cam_fx, value: 431.795 [ INFO] [1715416414.119085660]: Found parameter: laserMapping/cam_fy, value: 431.55 [ INFO] [1715416414.119216617]: Found parameter: laserMapping/cam_cx, value: 310.833 [ INFO] [1715416414.119335700]: Found parameter: laserMapping/cam_cy, value: 266.986 [ INFO] [1715416414.119455967]: Found parameter: laserMapping/cam_d0, value: -0.0944205 [ INFO] [1715416414.119578108]: Found parameter: laserMapping/cam_d1, value: 0.0946728 [ INFO] [1715416414.119710539]: Found parameter: laserMapping/cam_d2, value: -0.00807971 [ INFO] [1715416414.119854914]: Found parameter: laserMapping/cam_d3, value: 8.07461e-05 [ INFO ]: get point cloud at time: 1577836978.699827. [ INFO ]: get img at time: 1577836978.699827. FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836978.799653. [ INFO ]: get img at time: 1577836978.799653. [ INFO] [1715416424.098361639]: IMU Initializing: 0.5 % [ WARN] [1715416424.098402299]: Reset ImuProcess FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836978.899480. [ INFO ]: get img at time: 1577836978.899480. [ INFO] [1715416424.197875977]: IMU Initializing: 10.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836978.999310. [ INFO ]: get img at time: 1577836978.999310. [ INFO] [1715416424.297557771]: IMU Initializing: 20.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.099941. [ INFO ]: get img at time: 1577836979.099941. [ INFO] [1715416424.396768280]: IMU Initializing: 31.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.199771. [ INFO ]: get img at time: 1577836979.199771. [ INFO] [1715416424.497483387]: IMU Initializing: 41.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.299606. [ INFO ]: get img at time: 1577836979.299606. [ INFO] [1715416424.597653312]: IMU Initializing: 51.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.399457. [ INFO ]: get img at time: 1577836979.399457. [ INFO] [1715416424.697026123]: IMU Initializing: 61.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.499283. [ INFO ]: get img at time: 1577836979.499283. [ INFO] [1715416424.795842825]: IMU Initializing: 71.5 % FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.599930. [ INFO ]: get img at time: 1577836979.599930. [ INFO] [1715416424.896067917]: IMU Initializing: 81.5 % FAST-LIO not ready [ INFO] [1715416424.896374312]: IMU Initializing: 92.5 % FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.699775. [ INFO ]: get img at time: 1577836979.699775. [ INFO] [1715416424.996777721]: IMU Initializing: 93.0 % [ INFO] [1715416424.996812787]: IMU Initials: Gravity: -0.2714 -0.4027 -9.7980 0.9939; state.bias_g: 100.0000 100.0000 100.0000; acc covarience: 0.00111717 0.00062000 0.00097596; gry covarience: 0.00000725 0.00000545 0.00000694 [ INFO] [1715416424.996835888]: IMU Initials: Gravity: -0.2714 -0.4027 -9.7980 0.9939; state.bias_g: 0.0000 0.0000 0.0000; acc covarience: 0.11171720 0.06200038 0.09759611; gry covarience: 0.07248070 0.05450585 0.06941470 FAST-LIO not ready FAST-LIO not ready [ INFO ]: get point cloud at time: 1577836979.799607. [ INFO ]: get img at time: 1577836979.799607. [ VIO ]: Raw feature num: 0. [ VIO ]: Add 0 3D points. [ VIO ]: time: addFromSparseMap: 0.000002 addSparseMap: 0.000012 ComputeJ: 0.000001 addObservation: 0.000001 total time: 0.000017 ave_total: 8905.256738. [ INFO ]: get point cloud at time: 1577836979.899443. [ INFO ]: get img at time: 1577836979.899443. [ LIO ]: Raw feature num: 6435 downsamp num 4165 Map num: 2860. [ LIO ]: Using multi-processor, used core number: 4. [ LIO ]: time: fov_check: 0.000000 fov_check and readd: 0.001892 match: 0.000000 solve: 0.000000 ICP: 0.000250 map incre: 0.005021 total: 0.007164 icp: 0.000143 construct H: 0.000000. [ VIO ]: Raw feature num: 6435. [ VIO ]: Add 98 3D points. [ VIO ]: time: addFromSparseMap: 0.000001 addSparseMap: 0.001206 ComputeJ: 0.000000 addObservation: 0.000000 total time: 0.001207 ave_total: 8905.361562. [laserMapping-2] process has died [pid 9153, exit code -11, cmd /home/xuxumiao/catkin_ws/devel/lib/fast_livo/fastlivo_mapping __name:=laserMapping __log:=/home/xuxumiao/.ros/log/2738f926-0f71-11ef-8596-11d7ee4afbb7/laserMapping-2.log]. log file: /home/xuxumiao/.ros/log/2738f926-0f71-11ef-8596-11d7ee4afbb7/laserMapping-2*.log

Hello Sir, did you find the solution for this error ?
