### ISSUE TITLE
Problems running your own lab dataset mid360 and ouster128

### ISSUE THREAD

**Issue by Hohaizzz** [hku-mars/FAST-LIVO#97]
Displayed when running ouster128 recorded dataset
[ WARN] [1717073832.500779615]: Lidar selector debug:

Displayed when running mid360 recorded dataset

![2024-05-31 09-53-15屏幕截图](https://github.com/hku-mars/FAST-LIVO/assets/142421259/8bde505a-dbfe-417c-a234-38f83e06dc17)
![2024-05-31 09-54-07屏幕截图](https://github.com/hku-mars/FAST-LIVO/assets/142421259/e4103d74-5c1b-4056-ab21-9edfd74244bc)

I'd like to ask if no one else has had this problem, and I'd like to ask for help.

**Comment by xuankuzcr** [comment]
Can you send me the bag and the camera intrinsic and extrinsic parameters for testing? I will check if there are any issues.

**Comment by Hohaizzz** [comment]
mid360
![Uploading 2024-05-31 16-54-40屏幕截图.png…]()
ouster128
![2024-05-31 16-54-59屏幕截图](https://github.com/hku-mars/FAST-LIVO/assets/142421259/fea801ce-e209-4aa1-a523-a4b2af736bee)

**Comment by xuankuzcr** [comment]
Could you please provide me with the rosbag and the camera intrinsics?

**Comment by Hohaizzz** [comment]
尊敬的作者您好，已将scr文件和所录制的bag发送至您的qq邮箱，期待您的回复

**Comment by xuankuzcr** [comment]
您好，请通过邮箱zhengcr@connect.hku.hk发给我

**Comment by Hohaizzz** [comment]
已发送，麻烦您了

**Comment by xuankuzcr** [comment]
**This does not appear to be data from our lab. We have not publicly released any hard-synchronized data for MID360 and Ouster128.** Additionally, based on the data you provided, the camera and LiDAR are not time-synchronized. Currently, fast-livo1 only supports data that has been hard-synchronized.

**Comment by Hohaizzz** [comment]
好的，多谢作者，我后面将尝试将相机和雷达时间进行同步
